<?php

namespace common\models;

use Yii;
use yii\web\UploadedFile;

/**
 * This is the model class for table "teacher".
 *
 * @property int $id
 * @property string $name
 * @property string $surname
 * @property string $patronymic
 * @property string $position
 * @property string $img
 * @property string $description
 */
class Teacher extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'teacher';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name', 'surname', 'position', ], 'required'],
            [['description'], 'string'],
            [['name', 'surname', 'patronymic', 'position'], 'string', 'max' => 50],
            [['img'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'name' => Yii::t('app', 'Ismi'),
            'surname' => Yii::t('app', 'Familyasi'),
            'patronymic' => Yii::t('app', 'Otasining ismi'),
            'position' => Yii::t('app', 'Lavozimi'),
            'img' => Yii::t('app', 'Foto'),
            'description' => Yii::t('app', 'Tavsifi'),
        ];
    }
//return teacher.php
    public function getFullName(){
        return $this->surname." ".$this->name." ".$this->patronymic;
    }

    public function beforeSave($insert)
    {
        $time = time();
        $image = UploadedFile::getInstance($this,'img');
        if ($image != null){
            $filepath = Yii::getAlias('@frontend').'/web/images/'.$time.$image->name;
            $image->saveAs($filepath);
            $this->img='/images/'.$time.$image->name;
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function afterDelete()
    {
        @unlink(Yii::getAlias('@frontend').'/web'.$this->img);
        parent::afterDelete(); // TODO: Change the autogenerated stub
    }
}
